" so $VIM/vimrc
so $VIMRUNTIME/defaults.vim
set nocompatible
set viminfofile=$HOME/.vim/viminfo

if has('gui_running')
	set belloff=all
	set guioptions-=L
	set guioptions-=T
	set guioptions-=m
	set guioptions-=r
	let g:netrw_liststyle=3
	" colorscheme slate
	colorscheme default
	set guifont=Bitstream\ Vera\ Sans\ Mono\ 10
endif

" Tabline colors for tty
hi TabLine cterm=reverse

set sessionoptions=blank,buffers,curdir,folds,help,tabpages,winpos,winsize,resize,terminal
set splitbelow
set splitright
set number
set relativenumber
set ruler
set wildmenu
set wildoptions=pum " Vertical wild menu in cmdline
set showcmd
set lazyredraw
set scrolloff=8
set timeout
set timeoutlen=1000
set ttimeout
set ttimeoutlen=50
set mouse=n
set hidden

filetype plugin indent on

set tabstop=2
set shiftwidth=2
" set softtabstop=2
set expandtab
syntax on
set incsearch
set hlsearch
set noundofile
set noswapfile
set nobackup
set encoding=utf-8
set completeopt=menu,menuone,preview
let mapleader=" "

" Funny stuff
nnoremap <silent> <esc> :silent noh<CR>
nnoremap <leader> <Nop>

" Change marks
"nnoremap <Space><Space> /<++><CR>c4l
"nnoremap <leader>m i<++><Esc>l

" Encoding
"nnoremap <leader>u :set encoding=latin1<CR>
"nnoremap <leader>U :set encoding=utf-8<CR>

" Fonts (gui only)
"nnoremap <leader>fw :set guifont=Bitstream\ Vera\ Sans\ Mono\ 10<CR>
"nnoremap <leader>fe :set guifont=Bitstream\ Vera\ Sans\ Mono\ 12<CR>
"nnoremap <leader>fr :set guifont=Bitstream\ Vera\ Sans\ Mono\ 16<CR>

" Configuring
nnoremap <leader>r :so $MYVIMRC<CR>
nnoremap <leader>E :tabnew $MYVIMRC<CR>

" C++ helpers
"nnoremap <leader>inc a#include 
"nnoremap <leader>ifn a#ifndef <++><CR>#define <++><CR>#endif<Esc>?<++><CR>n<C-v>j3lc

" Window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Buffers
nnoremap <leader>b :ls<CR>:b<Space>
nnoremap <leader>d :ls<CR>:bd<Space>
nnoremap <leader>n :bnext<CR>
nnoremap <leader>p :bprev<CR>
nnoremap <leader>x :bd<CR>
nnoremap <leader>X :bd!<CR>
nnoremap <leader>e :enew<CR>
nnoremap <leader><Tab> <C-^>

" Tabs
nnoremap <leader>tn :tabnew<CR>
nnoremap <leader>tx :tabclose<CR>

nnoremap <M-1> 1gt
nnoremap <M-2> 2gt
nnoremap <M-3> 3gt
nnoremap <M-4> 4gt
nnoremap <M-5> 5gt
nnoremap <M-6> 6gt
nnoremap <M-7> 7gt
nnoremap <M-8> 8gt
nnoremap <M-9> 9gt

" Terminal fixes
tnoremap <C-x> <C-\><C-n>
tnoremap <C-w> <C-w>.
tnoremap <C-\><C-x> <C-x>

" Movement in insert mode
inoremap <C-h> <left>
inoremap <C-j> <down>
inoremap <C-k> <up>
inoremap <C-l> <right>

" Matching pairs
inoremap " ""<C-G>U<left>
inoremap "<esc> "<esc>
inoremap "" ""

inoremap ' ''<C-G>U<left>
inoremap '<esc> '<esc>
inoremap '' ''

inoremap ( ()<C-G>U<left>
inoremap (<esc> (<esc>
inoremap () ()

inoremap [ []<C-G>U<left>
inoremap [<esc> [<esc>
inoremap [] []

inoremap { {}<C-G>U<left>
inoremap {<esc> {<esc>
inoremap {} {}

inoremap < <><C-G>U<left>
inoremap <<esc> <<esc>
inoremap <<Space> < 
inoremap <= <=
inoremap << <<

" TODO make it so this does not close them on other tabs
function! CleanNoNameEmptyBuffers()
    let buffers = filter(range(1, bufnr('$')), 'buflisted(v:val) 
      \ && empty(bufname(v:val)) && empty(win_findbuf(v:val))
      \ && (getbufline(v:val, 1, "$") == [""])')
    if !empty(buffers)
        exe 'bd '.join(buffers, ' ')
    else
        echo 'No buffer deleted'
    endif
endfunction

" Plugins
call plug#begin('~/.vim/plugged')
Plug 'habamax/vim-godot'
Plug 'mattn/emmet-vim'
Plug 'plasticboy/vim-markdown'
Plug 'xuhdev/vim-latex-live-preview', {'for': 'tex'}
Plug 'rrethy/vim-hexokinase', { 'do': 'make hexokinase' }
Plug 'tikhomirov/vim-glsl'
Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() }, 'for': ['markdown', 'vim-plug']}
call plug#end()

" vim-markdown
let g:vim_markdown_new_list_item_indent = 0

" Hexokinase
let g:Hexokinase_ftEnabled = []
let g:Hexokinase_highlighters = [ 'sign_column', 'background', 'backgroundfull', 'foreground', 'foregroundfull' ]

let g:Hexokinase_optInPatterns = [ 'full_hex', 'triple_hex', 'rgb', 'rgba', 'hsl', 'hsla', 'colour_names' ]

let g:vim_markdown_folding_disabled=1
